name: Continious Deployment Unreal Prject
run-name: ${{ github.actor }} builds the app
on:
  push:
    branches:
      - "**"

    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  Build-and-deploy:
    runs-on: local-windows
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: build-Project
        run: |
          cd CICDscripts
          ls
          ./buildAPK.bat "..\"  "..\\Builds\\beeyougames.apk" "Android"
      - name: Download Butler
        run: |
          curl -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          powershell Expand-Archive butler.zip
      - name: Publish the build Folder
        run: |
          ./butler/butler.exe push .\Builds beeyougames/beeyou-games-test:android --userversion ${{  github.ref_name }}
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
